### ISSUE TITLE
Promijeniti poruku pri netočnom logiranju

### ISSUE THREAD

**Issue by nikovrdoljak** [karlozrilic/pzw-zavrsni#2]
Prilikom netočnog logiranja odaješ što je korisnik neispravno upisao (login name ili password). Preporuka je u takvim slučajevima napisati da je "Upisali ste neispravno korisničko ime ili zaporku", a ne odavati što je krivo, jer potencijalni haker na taj način dobija previše informacija.

**Comment by karlozrilic** [comment]
Promijenjena je poruka u "Upisali ste neispravno korisničko ime ili zaporku!"
