### ISSUE TITLE
Uvesti validaciju na numerička polja

### ISSUE THREAD

**Issue by sbuljat** [karlozrilic/pzw-zavrsni#3]
Prilikom promjene cijene pizze (obična & jumbo) potrebno je uvesti validaciju polja kako bi se dozvolile samo numeričke vrijednosti. Trenutno se pri pokušaju unosa "string" dogodi greška 500.

**Comment by karlozrilic** [comment]
Pošto ne postoji built in wtform validator za integer ili float stavio sam da kada se forma ne uspije validirati da izbacuje upozorenje na stranici o pogrešnom unosu

**Comment by sbuljat** [comment]
Bi li se možda mogao NumberRange iskoristiti? Može postojati max cijena, npr. neki jako veliki broj.

**Comment by karlozrilic** [comment]
NumberRange ne bi funkcionirao kada bi korisnik upisao string jer bi i dalje vraćao da forma nije validna pa sam napravio nekakav custom validator za unos i dodao upozorenje za krivo učitani file
